// Code generated by mockery v2.42.1. DO NOT EDIT.

package ports

import (
	domain "github.com/lamtrinh/go-ecom-hexagon/order-service/internal/application/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockDBPort is an autogenerated mock type for the DBPort type
type MockDBPort struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *MockDBPort) Get(_a0 int32) (domain.Order, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(int32) (domain.Order, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int32) domain.Order); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}

	if rf, ok := ret.Get(1).(func(int32) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0
func (_m *MockDBPort) Save(_a0 *domain.Order) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Order) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockDBPort creates a new instance of MockDBPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBPort {
	mock := &MockDBPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
