// Code generated by mockery v2.42.1. DO NOT EDIT.

package ports

import (
	domain "github.com/lamtrinh/go-ecom-hexagon/order-service/internal/application/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentPort is an autogenerated mock type for the PaymentPort type
type MockPaymentPort struct {
	mock.Mock
}

// Charge provides a mock function with given fields: _a0
func (_m *MockPaymentPort) Charge(_a0 *domain.Order) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Charge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Order) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockPaymentPort creates a new instance of MockPaymentPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentPort {
	mock := &MockPaymentPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
